export enum tagTypes {
  auth = "auth",
  user = "user",
  customer = "customer",
  customerAgent = "customer-agent",
  technician = "technician",
  admin = "admin",
  superAdmin = "super-admin",
  role = "role",
  faq = "faq",
  blog = "blog",
  feedBack = "feedback",
  timeSlot = "time-slot",
  booking = "booking",
  services = "services",
  review = "review",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.auth,
  tagTypes.customer,
  tagTypes.customerAgent,
  tagTypes.technician,
  tagTypes.admin,
  tagTypes.superAdmin,
  tagTypes.role,
  tagTypes.faq,
  tagTypes.blog,
  tagTypes.feedBack,
  tagTypes.timeSlot,
  tagTypes.booking,
  tagTypes.services,
  tagTypes.review,
];
